### ISSUE TITLE
Practica 6 Contratos inteligentes

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-6-contratos-inteligentes-team-noble#1]
[Practica contrato inteligente.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-contratos-inteligentes-team-noble/files/8654997/Practica.contrato.inteligente.pdf)

**Comment by CxrlosMX** [comment]
Buen trabajo compañeros, calificación obtenida: 20%

**Comment by josealfredo79** [comment]
Pueden mandar su diagrama de clases, por favor para corroborar que sea de acuerdo a su proyecto

**Comment by josealfredo79** [comment]
Para poder validar su trabajo por favor

**Comment by josealfredo79** [comment]
Y también subir su código fuente a la organización Near University Tec de Tlaxiaco

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/170774063-1636d7be-f2ad-49e1-9700-38c0f8b04ce2.png)
 No ha subido al repositorio de Near University Tec de Tlaxiaco las instrucciones para compilar y desplegar el contrato

**Comment by IsraelNicolas61** [comment]
https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-IMA-G/issues/1#issue-1196776739
